[package]
name = "xof_py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "xof_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.0", features = ["gil-refs"] }
sha3 = "0.10.8"
